home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    methods: GET
    defaults:
        template: 'home.html.twig'

main_controllers:
    resource:
        path: ../src/Controller/Main
        namespace: App\Controller\Main
    type: attribute

admin_controllers:
    name_prefix: 'admin.'
    prefix: '/admin'
    resource:
        path: ../src/Controller/Admin
        namespace: App\Controller\Admin
    type: attribute

#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute
