home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    methods: GET
    defaults:
        template: 'home.html.twig'

blog:
    path: /blog
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    methods: GET
    defaults:
        template: 'blog/index.html.twig'

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
